In [24]:
#Mount google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [25]:
#Import necessary libraries
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [45]:
#1.	Load the dataset into a Pandas DataFrame and extract the text and label columns.
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Natural Language Processing/cleaned_updated_data.csv",usecols=['review_text', 'sentiment'])
df

documents = df['review_text']
print(f"Number of documents: {len(documents)}")
print(f"First 5 documents:\n{documents.head()}")

Number of documents: 100
First 5 documents:
0    Taste of the food is nice but the dining and h...
1    Seemed to be very dark in the catalogue but wh...
2    Material is not nice but I like print and patt...
3    The quality is not anything that I'd put up in...
4    Durability is a concern but apart from that al...
Name: review_text, dtype: object

In [46]:
#2.	Perform tokenization on all documents and store the tokens corresponding to each document.
import nltk
from nltk.tokenize import word_tokenize

# Download the 'punkt' tokenizer models required for word_tokenize
nltk.download('punkt_tab')

# Tokenize each document
tokenized_documents = [word_tokenize(doc) for doc in documents.astype(str)]

print(f"Number of tokenized documents: {len(tokenized_documents)}")
print(f"First 5 tokenized documents:\n{tokenized_documents[:5]}")

Number of tokenized documents: 100
First 5 tokenized documents:
[['Taste', 'of', 'the', 'food', 'is', 'nice', 'but', 'the', 'dining', 'and', 'hygiene', 'of', 'the', 'restaurant', 'was', 'not', 'nice'], ['Seemed', 'to', 'be', 'very', 'dark', 'in', 'the', 'catalogue', 'but', 'when', 'arrived', 'the', 'color', 'fades', 'after', 'washing'], ['Material', 'is', 'not', 'nice', 'but', 'I', 'like', 'print', 'and', 'pattern', ',', 'for', 'this', 'cost', 'it', 'worth', 'only'], ['The', 'quality', 'is', 'not', 'anything', 'that', 'I', "'d", 'put', 'up', 'in', 'my', 'home', 'to', 'try'], ['Durability', 'is', 'a', 'concern', 'but', 'apart', 'from', 'that', 'all', 'other', 'factors', 'are', 'good']]

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [47]:
#3.	Apply case folding by converting all tokens to lowercase.
casefold_tokens= [[token.casefold() for token in doc] for doc in tokenized_documents]
casefold_tokens

[['taste',
  'of',
  'the',
  'food',
  'is',
  'nice',
  'but',
  'the',
  'dining',
  'and',
  'hygiene',
  'of',
  'the',
  'restaurant',
  'was',
  'not',
  'nice'],
 ['seemed',
  'to',
  'be',
  'very',
  'dark',
  'in',
  'the',
  'catalogue',
  'but',
  'when',
  'arrived',
  'the',
  'color',
  'fades',
  'after',
  'washing'],
 ['material',
  'is',
  'not',
  'nice',
  'but',
  'i',
  'like',
  'print',
  'and',
  'pattern',
  ',',
  'for',
  'this',
  'cost',
  'it',
  'worth',
  'only'],
 ['the',
  'quality',
  'is',
  'not',
  'anything',
  'that',
  'i',
  "'d",
  'put',
  'up',
  'in',
  'my',
  'home',
  'to',
  'try'],
 ['durability',
  'is',
  'a',
  'concern',
  'but',
  'apart',
  'from',
  'that',
  'all',
  'other',
  'factors',
  'are',
  'good'],
 ['the',
  'product',
  'is',
  'nice',
  'only',
  'but',
  'not',
  'as',
  'expected',
  'because',
  'of',
  'the',
  'fitting'],
 ['actign',
  'is',
  'good',
  'and',
  'fight',
  'scenes',
  'were',
  'nice',
  'but',
  'not',
  'the',
  'story'],
 ['the',
  'experience',
  'was',
  'good',
  'and',
  'i',
  'would',
  'recommend',
  'it',
  'to',
  'others'],
 ['water',
  'leakage',
  'issues',
  'because',
  'water',
  'pours',
  'out',
  'of',
  'the',
  'holes',
  '.'],
 ['this', 'is', 'one', 'of', 'the', 'best', 'purchases', 'i', 'have', 'made'],
 ['this', 'is', 'one', 'of', 'the', 'worst', 'products', 'i', 'have', 'used'],
 ['good',
  'material',
  'and',
  'patterns',
  'but',
  'don',
  '’',
  't',
  'like',
  'the',
  'fitting'],
 ['the',
  'delivery',
  'was',
  'fast',
  'and',
  'the',
  'packaging',
  'was',
  'secure'],
 ['the',
  'product',
  'quality',
  'is',
  'excellent',
  'and',
  'exceeded',
  'my',
  'expectations'],
 ['it',
  '’',
  's',
  'high-quality',
  ',',
  'powerful',
  ',',
  'lightweight',
  ',',
  'and',
  'does',
  'a',
  'great',
  'job'],
 ['i', 'am', 'very', 'satisfied', 'with', 'the', 'service', 'provided'],
 ['it', 'does', 'what', 'it', 'is', 'supposed', 'to', 'do'],
 ['it', 'saves', 'a', 'lot', 'of', 'time', 'and', 'effort'],
 ['the', 'product', 'stopped', 'working', 'after', 'a', 'few', 'days'],
 ['the', 'interface', 'is', 'clean', 'and', 'easy', 'to', 'use'],
 ['the', 'app', 'is', 'usable', 'but', 'not', 'very', 'exciting'],
 ['you', 'can', 'watch', 'the', 'movie', 'but', 'not', 'worthable'],
 ['the', 'updates', 'have', 'improved', 'the', 'product', 'a', 'lot'],
 ['ever', 'worst', 'utter', 'flop', 'movie', 'in', 'the', 'world'],
 ['it', 'looks', 'fine', 'but', 'could', 'be', 'improved'],
 ['amazing', 'performance', 'and', 'great', 'value', 'for', 'money'],
 ['the', 'quality', 'is', 'decent', 'for', 'the', 'price'],
 ['i', 'think', 'the', 'product', 'meets', 'basic', 'expectations'],
 ['i', 'am', 'disappointed', 'with', 'the', 'overall', 'performance'],
 ['delivery', 'was', 'delayed', 'and', 'packaging', 'was', 'damaged'],
 ['the', 'product', 'is', 'reliable', 'and', 'well', 'designed'],
 ['the', 'support', 'team', 'resolved', 'my', 'issue', 'quickly'],
 ['the', 'experience', 'was', 'neither', 'good', 'nor', 'bad'],
 ['the', 'quality', 'is', 'very', 'poor', 'and', 'unacceptable'],
 ['no', 'major', 'complaints', ',', 'but', 'no', 'highlights', 'either'],
 ['doesn', '’', 't', 'take', 'up', 'a', 'ton', 'of', 'space'],
 ['everything', 'was', 'smooth', 'from', 'start', 'to', 'finish'],
 ['i', 'would', 'not', 'recommend', 'this', 'to', 'anyone'],
 ['works', 'well', ',', 'heats', 'fast', ',', 'good', 'steam', 'output', '.'],
 ['i', 'am', 'impressed', 'with', 'the', 'build', 'quality'],
 ['the', 'product', 'is', 'neither', 'impressive', 'nor', 'disappointing'],
 ['i', 'faced', 'many', 'issues', 'while', 'using', 'it'],
 ['i', 'have', 'mixed', 'feelings', 'about', 'this', 'product'],
 ['the', 'design', 'feels', 'cheap', 'and', 'poorly', 'made'],
 ['nice', 'iron', ',', 'good', 'value', 'for', 'the', 'price', '.'],
 ['i', 'am', 'very', 'pleased', 'with', 'the', 'results'],
 ['works', 'flawlessly', 'even', 'under', 'heavy', 'use'],
 ['it', 'is', 'okay', 'but', 'nothing', 'special'],
 ['the', 'experience', 'was', 'frustrating', 'and', 'annoying'],
 ['not', 'worth', 'the', 'money', 'at', 'all'],
 ['the', 'features', 'are', 'impressive', 'and', 'useful'],
 ['very', 'happy', 'with', 'the', 'overall', 'experience'],
 ['customer', 'support', 'was', 'helpful', 'and', 'responsive'],
 ['everything', 'worked', 'perfectly', 'without', 'any', 'issues'],
 ['the', 'app', 'runs', 'fast', 'and', 'efficiently'],
 ['the', 'product', 'feels', 'premium', 'and', 'durable'],
 ['the', 'performance', 'is', 'slow', 'and', 'unreliable'],
 ['i', 'am', 'unhappy', 'with', 'this', 'purchase'],
 ['highly', 'recommended', 'for', 'beginners', 'and', 'professionals'],
 ['i', 'would', 'definitely', 'buy', 'this', 'again'],
 ['customer', 'service', 'was', 'rude', 'and', 'unhelpful'],
 ['the', 'service', 'was', 'average', 'and', 'acceptable'],
 ['i', 'really', 'enjoyed', 'using', 'this', 'application'],
 ['it', 'works', 'most', 'of', 'the', 'time'],
 ['the', 'instructions', 'were', 'unclear', 'and', 'confusing'],
 ['the', 'product', 'broke', 'within', 'a', 'week'],
 ['it', 'does', 'not', 'work', 'as', 'advertised'],
 ['it', 'functions', 'normally', 'without', 'problems'],
 ['the', 'setup', 'process', 'was', 'straightforward'],
 ['too', 'many', 'bugs', 'and', 'errors'],
 ['i', 'regret', 'buying', 'this', 'product'],
 ['smooth', 'performance', 'and', 'great', 'usability'],
 ['the', 'response', 'time', 'was', 'reasonable'],
 ['the', 'product', 'works', 'as', 'described'],
 ['it', 'does', "n't", 'get', 'hot', 'enough'],
 ['nice', 'only', 'but', 'not', 'good'],
 ['the', 'service', 'exceeded', 'my', 'expectations'],
 ['the', 'product', 'arrived', 'on', 'time'],
 ['great', 'user', 'experience', 'and', 'design'],
 ['the', 'application', 'crashes', 'frequently'],
 ['overall', 'a', 'fantastic', 'experience'],
 ['the', 'experience', 'was', 'standard'],
 ['nothing', 'particularly', 'stands', 'out'],
 ['the', 'performance', 'is', 'acceptable'],
 ['effective', 'at', 'quickly', 'processing'],
 ['worth', 'every', 'penny', 'spent'],
 ['customer', 'support', 'never', 'responded'],
 ['excellent', 'attention', 'to', 'detail'],
 ['worst', 'product', 'ever', 'bought'],
 ['not', 'worth', 'the', 'price'],
 ['i', 'am', 'impressed'],
 ['do', 'not', 'buy', '.'],
 ['premium', 'quality'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['nan']]

In [48]:
#4.	Remove stop-words from the tokenized documents.
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

english_stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Stemming-based Representation

In [49]:
#5. Apply stemming to the filtered tokens and store the stemmed tokens separately.
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

stemmed_tokens = [[stemmer.stem(word) for word in doc_tokens] for doc_tokens in casefold_tokens]
stemmed_tokens

[['tast',
  'of',
  'the',
  'food',
  'is',
  'nice',
  'but',
  'the',
  'dine',
  'and',
  'hygien',
  'of',
  'the',
  'restaur',
  'wa',
  'not',
  'nice'],
 ['seem',
  'to',
  'be',
  'veri',
  'dark',
  'in',
  'the',
  'catalogu',
  'but',
  'when',
  'arriv',
  'the',
  'color',
  'fade',
  'after',
  'wash'],
 ['materi',
  'is',
  'not',
  'nice',
  'but',
  'i',
  'like',
  'print',
  'and',
  'pattern',
  ',',
  'for',
  'thi',
  'cost',
  'it',
  'worth',
  'onli'],
 ['the',
  'qualiti',
  'is',
  'not',
  'anyth',
  'that',
  'i',
  "'d",
  'put',
  'up',
  'in',
  'my',
  'home',
  'to',
  'tri'],
 ['durabl',
  'is',
  'a',
  'concern',
  'but',
  'apart',
  'from',
  'that',
  'all',
  'other',
  'factor',
  'are',
  'good'],
 ['the',
  'product',
  'is',
  'nice',
  'onli',
  'but',
  'not',
  'as',
  'expect',
  'becaus',
  'of',
  'the',
  'fit'],
 ['actign',
  'is',
  'good',
  'and',
  'fight',
  'scene',
  'were',
  'nice',
  'but',
  'not',
  'the',
  'stori'],
 ['the',
  'experi',
  'wa',
  'good',
  'and',
  'i',
  'would',
  'recommend',
  'it',
  'to',
  'other'],
 ['water',
  'leakag',
  'issu',
  'becaus',
  'water',
  'pour',
  'out',
  'of',
  'the',
  'hole',
  '.'],
 ['thi', 'is', 'one', 'of', 'the', 'best', 'purchas', 'i', 'have', 'made'],
 ['thi', 'is', 'one', 'of', 'the', 'worst', 'product', 'i', 'have', 'use'],
 ['good',
  'materi',
  'and',
  'pattern',
  'but',
  'don',
  '’',
  't',
  'like',
  'the',
  'fit'],
 ['the', 'deliveri', 'wa', 'fast', 'and', 'the', 'packag', 'wa', 'secur'],
 ['the', 'product', 'qualiti', 'is', 'excel', 'and', 'exceed', 'my', 'expect'],
 ['it',
  '’',
  's',
  'high-qual',
  ',',
  'power',
  ',',
  'lightweight',
  ',',
  'and',
  'doe',
  'a',
  'great',
  'job'],
 ['i', 'am', 'veri', 'satisfi', 'with', 'the', 'servic', 'provid'],
 ['it', 'doe', 'what', 'it', 'is', 'suppos', 'to', 'do'],
 ['it', 'save', 'a', 'lot', 'of', 'time', 'and', 'effort'],
 ['the', 'product', 'stop', 'work', 'after', 'a', 'few', 'day'],
 ['the', 'interfac', 'is', 'clean', 'and', 'easi', 'to', 'use'],
 ['the', 'app', 'is', 'usabl', 'but', 'not', 'veri', 'excit'],
 ['you', 'can', 'watch', 'the', 'movi', 'but', 'not', 'worthabl'],
 ['the', 'updat', 'have', 'improv', 'the', 'product', 'a', 'lot'],
 ['ever', 'worst', 'utter', 'flop', 'movi', 'in', 'the', 'world'],
 ['it', 'look', 'fine', 'but', 'could', 'be', 'improv'],
 ['amaz', 'perform', 'and', 'great', 'valu', 'for', 'money'],
 ['the', 'qualiti', 'is', 'decent', 'for', 'the', 'price'],
 ['i', 'think', 'the', 'product', 'meet', 'basic', 'expect'],
 ['i', 'am', 'disappoint', 'with', 'the', 'overal', 'perform'],
 ['deliveri', 'wa', 'delay', 'and', 'packag', 'wa', 'damag'],
 ['the', 'product', 'is', 'reliabl', 'and', 'well', 'design'],
 ['the', 'support', 'team', 'resolv', 'my', 'issu', 'quickli'],
 ['the', 'experi', 'wa', 'neither', 'good', 'nor', 'bad'],
 ['the', 'qualiti', 'is', 'veri', 'poor', 'and', 'unaccept'],
 ['no', 'major', 'complaint', ',', 'but', 'no', 'highlight', 'either'],
 ['doesn', '’', 't', 'take', 'up', 'a', 'ton', 'of', 'space'],
 ['everyth', 'wa', 'smooth', 'from', 'start', 'to', 'finish'],
 ['i', 'would', 'not', 'recommend', 'thi', 'to', 'anyon'],
 ['work', 'well', ',', 'heat', 'fast', ',', 'good', 'steam', 'output', '.'],
 ['i', 'am', 'impress', 'with', 'the', 'build', 'qualiti'],
 ['the', 'product', 'is', 'neither', 'impress', 'nor', 'disappoint'],
 ['i', 'face', 'mani', 'issu', 'while', 'use', 'it'],
 ['i', 'have', 'mix', 'feel', 'about', 'thi', 'product'],
 ['the', 'design', 'feel', 'cheap', 'and', 'poorli', 'made'],
 ['nice', 'iron', ',', 'good', 'valu', 'for', 'the', 'price', '.'],
 ['i', 'am', 'veri', 'pleas', 'with', 'the', 'result'],
 ['work', 'flawlessli', 'even', 'under', 'heavi', 'use'],
 ['it', 'is', 'okay', 'but', 'noth', 'special'],
 ['the', 'experi', 'wa', 'frustrat', 'and', 'annoy'],
 ['not', 'worth', 'the', 'money', 'at', 'all'],
 ['the', 'featur', 'are', 'impress', 'and', 'use'],
 ['veri', 'happi', 'with', 'the', 'overal', 'experi'],
 ['custom', 'support', 'wa', 'help', 'and', 'respons'],
 ['everyth', 'work', 'perfectli', 'without', 'ani', 'issu'],
 ['the', 'app', 'run', 'fast', 'and', 'effici'],
 ['the', 'product', 'feel', 'premium', 'and', 'durabl'],
 ['the', 'perform', 'is', 'slow', 'and', 'unreli'],
 ['i', 'am', 'unhappi', 'with', 'thi', 'purchas'],
 ['highli', 'recommend', 'for', 'beginn', 'and', 'profession'],
 ['i', 'would', 'definit', 'buy', 'thi', 'again'],
 ['custom', 'servic', 'wa', 'rude', 'and', 'unhelp'],
 ['the', 'servic', 'wa', 'averag', 'and', 'accept'],
 ['i', 'realli', 'enjoy', 'use', 'thi', 'applic'],
 ['it', 'work', 'most', 'of', 'the', 'time'],
 ['the', 'instruct', 'were', 'unclear', 'and', 'confus'],
 ['the', 'product', 'broke', 'within', 'a', 'week'],
 ['it', 'doe', 'not', 'work', 'as', 'advertis'],
 ['it', 'function', 'normal', 'without', 'problem'],
 ['the', 'setup', 'process', 'wa', 'straightforward'],
 ['too', 'mani', 'bug', 'and', 'error'],
 ['i', 'regret', 'buy', 'thi', 'product'],
 ['smooth', 'perform', 'and', 'great', 'usabl'],
 ['the', 'respons', 'time', 'wa', 'reason'],
 ['the', 'product', 'work', 'as', 'describ'],
 ['it', 'doe', "n't", 'get', 'hot', 'enough'],
 ['nice', 'onli', 'but', 'not', 'good'],
 ['the', 'servic', 'exceed', 'my', 'expect'],
 ['the', 'product', 'arriv', 'on', 'time'],
 ['great', 'user', 'experi', 'and', 'design'],
 ['the', 'applic', 'crash', 'frequent'],
 ['overal', 'a', 'fantast', 'experi'],
 ['the', 'experi', 'wa', 'standard'],
 ['noth', 'particularli', 'stand', 'out'],
 ['the', 'perform', 'is', 'accept'],
 ['effect', 'at', 'quickli', 'process'],
 ['worth', 'everi', 'penni', 'spent'],
 ['custom', 'support', 'never', 'respond'],
 ['excel', 'attent', 'to', 'detail'],
 ['worst', 'product', 'ever', 'bought'],
 ['not', 'worth', 'the', 'price'],
 ['i', 'am', 'impress'],
 ['do', 'not', 'buy', '.'],
 ['premium', 'qualiti'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['nan'],
 ['nan']]

In [50]:
#6.	Create a new column containing the final preprocessed text after stemming by joining the stemmed tokens.
df['stemtokens'] = [' '.join(token) for token in stemmed_tokens]
df

,review_text,sentiment,stemtokens
0,Taste of the food is nice but the dining and h...,neutral,tast of the food is nice but the dine and hygi...
1,Seemed to be very dark in the catalogue but wh...,negative,seem to be veri dark in the catalogu but when ...
2,Material is not nice but I like print and patt...,neutral,materi is not nice but i like print and patter...
3,The quality is not anything that I'd put up in...,negative,the qualiti is not anyth that i 'd put up in m...
4,Durability is a concern but apart from that al...,neutral,durabl is a concern but apart from that all ot...
...,...,...,...
95,NaN,positive,nan
96,NaN,NaN,nan
97,NaN,NaN,nan
98,NaN,NaN,nan
99,NaN,neutral,nan

In [51]:
#7.	Construct the Bag-of-Words vocabulary using the stemmed text.
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['stemtokens'])

In [52]:
#8.	Determine the size of the stemming-based vocabulary and list the top 10 most frequent words.
vocab = vectorizer.get_feature_names_out()
print(f"Size of the stemming-based vocabulary: {len(vocab)}")
print(f"Top 10 most frequent words: {vocab[:10]}")

Size of the stemming-based vocabulary: 262
Top 10 most frequent words: ['about' 'accept' 'actign' 'advertis' 'after' 'again' 'all' 'am' 'amaz'
 'and']

In [53]:
#9.	Represent each document using Bag-of-Words frequency vectors and generate the document–term matrix (DTM) for the stemmed text.
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['stemtokens'])

Lemmatization-based Representation

In [54]:
#10. Apply lemmatization to the filtered tokens and store the lemmatized tokens separately.
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

# Download necessary NLTK data for WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

lemmatized_documents = []
for doc_tokens in casefold_tokens:
    # Filter out stop words first (assuming 'english_stop_words' is defined from previous steps)
    filtered_tokens_after_stopwords = [word for word in doc_tokens if word not in english_stop_words]
    # Then, lemmatize the remaining tokens
    lemmatized_tokens_for_doc = [lemmatizer.lemmatize(word) for word in filtered_tokens_after_stopwords]
    lemmatized_documents.append(lemmatized_tokens_for_doc)

print(f"Number of lemmatized documents: {len(lemmatized_documents)}")
print(f"First 5 lemmatized documents:\n{lemmatized_documents[:5]}")

Number of lemmatized documents: 100
First 5 lemmatized documents:
[['taste', 'food', 'nice', 'dining', 'hygiene', 'restaurant', 'nice'], ['seemed', 'dark', 'catalogue', 'arrived', 'color', 'fade', 'washing'], ['material', 'nice', 'like', 'print', 'pattern', ',', 'cost', 'worth'], ['quality', 'anything', "'d", 'put', 'home', 'try'], ['durability', 'concern', 'apart', 'factor', 'good']]

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [55]:
#11.	Create a new column containing the final preprocessed text after lemmatization by joining the lemmatized tokens.
df['lemmtokens'] = [' '.join(token) for token in lemmatized_documents]
df

,review_text,sentiment,stemtokens,lemmtokens
0,Taste of the food is nice but the dining and h...,neutral,tast of the food is nice but the dine and hygi...,taste food nice dining hygiene restaurant nice
1,Seemed to be very dark in the catalogue but wh...,negative,seem to be veri dark in the catalogu but when ...,seemed dark catalogue arrived color fade washing
2,Material is not nice but I like print and patt...,neutral,materi is not nice but i like print and patter...,"material nice like print pattern , cost worth"
3,The quality is not anything that I'd put up in...,negative,the qualiti is not anyth that i 'd put up in m...,quality anything 'd put home try
4,Durability is a concern but apart from that al...,neutral,durabl is a concern but apart from that all ot...,durability concern apart factor good
...,...,...,...,...
95,NaN,positive,nan,nan
96,NaN,NaN,nan,nan
97,NaN,NaN,nan,nan
98,NaN,NaN,nan,nan
99,NaN,neutral,nan,nan

In [56]:
#12. Construct the Bag-of-Words vocabulary using the lemmatized text.
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X_lemmatized = vectorizer.fit_transform(df['lemmtokens'])

In [57]:
#13.	Determine the size of the lemmatization-based vocabulary and list the top 10 most frequent words.
vocab = vectorizer.get_feature_names_out()
print(f"Size of the lemmatization-based vocabulary: {len(vocab)}")
print(f"Top 10 most frequent words: {vocab[:10]}")

Size of the lemmatization-based vocabulary: 228
Top 10 most frequent words: ['acceptable' 'actign' 'advertised' 'amazing' 'annoying' 'anyone'
 'anything' 'apart' 'app' 'application']

In [58]:
#14.	Represent each document using Bag-of-Words frequency vectors and generate the document–term matrix (DTM) for the lemmatized text.
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X_lemmatized = vectorizer.fit_transform(df['lemmtokens'])

In [59]:
#15. Select any one document and display its BoW vector from:
#• the stemming-based DTM
#• the lemmatization-based DTM

from sklearn.feature_extraction.text import CountVectorizer

# Document index to display (e.g., the first document)
doc_index = 0

# --- Stemming-based DTM ---
stem_vectorizer = CountVectorizer()
X_stemmed = stem_vectorizer.fit_transform(df['stemtokens'])
stem_vocab = stem_vectorizer.get_feature_names_out()

# Get the BoW vector for the selected document from the stemmed DTM
stem_bow_vector = X_stemmed[doc_index].toarray().flatten()

# Display the stemmed BoW vector (word: count)
print(f"\nBoW vector for document {doc_index} (stemming-based):")
stem_bow_representation = {stem_vocab[i]: count for i, count in enumerate(stem_bow_vector) if count > 0}
print(stem_bow_representation)

# --- Lemmatization-based DTM ---
lemma_vectorizer = CountVectorizer()
X_lemmatized = lemma_vectorizer.fit_transform(df['lemmtokens'])
lemma_vocab = lemma_vectorizer.get_feature_names_out()

# Get the BoW vector for the selected document from the lemmatized DTM
lemma_bow_vector = X_lemmatized[doc_index].toarray().flatten()

# Display the lemmatized BoW vector (word: count)
print(f"\nBoW vector for document {doc_index} (lemmatization-based):")
lemma_bow_representation = {lemma_vocab[i]: count for i, count in enumerate(lemma_bow_vector) if count > 0}
print(lemma_bow_representation)

BoW vector for document 0 (stemming-based):
{'and': np.int64(1), 'but': np.int64(1), 'dine': np.int64(1), 'food': np.int64(1), 'hygien': np.int64(1), 'is': np.int64(1), 'nice': np.int64(2), 'not': np.int64(1), 'of': np.int64(2), 'restaur': np.int64(1), 'tast': np.int64(1), 'the': np.int64(3), 'wa': np.int64(1)}

BoW vector for document 0 (lemmatization-based):
{'dining': np.int64(1), 'food': np.int64(1), 'hygiene': np.int64(1), 'nice': np.int64(2), 'restaurant': np.int64(1), 'taste': np.int64(1)}

In [60]:
#16. Identify words that appear in most documents and words that appear in very few documents, and discuss their significance in text classification.

import numpy as np

# --- Stemming-based DTM ---
# The vectorizer and X_stemmed are already created in step 15
# stem_vectorizer, X_stemmed, and stem_vocab from previous steps

# Calculate document frequency for stemming-based DTM
# A term is present in a document if its count > 0
stem_doc_frequencies = np.sum(X_stemmed > 0, axis=0).A1

# Sort by frequency
stem_sorted_indices = stem_doc_frequencies.argsort()

print("\n--- Stemming-based Analysis ---")
print(f"Total number of documents: {X_stemmed.shape[0]}")

print("\nWords appearing in most documents (Stemming):")
for i in stem_sorted_indices[::-1][:10]: # Top 10 most frequent by document
    print(f"'{stem_vocab[i]}': appears in {stem_doc_frequencies[i]} documents")

print("\nWords appearing in very few documents (Stemming):")
for i in stem_sorted_indices[:10]: # Top 10 least frequent by document
    print(f"'{stem_vocab[i]}': appears in {stem_doc_frequencies[i]} documents")


# --- Lemmatization-based DTM ---
# The vectorizer and X_lemmatized are already created in step 15
# lemma_vectorizer, X_lemmatized, and lemma_vocab from previous steps

# Calculate document frequency for lemmatization-based DTM
lemma_doc_frequencies = np.sum(X_lemmatized > 0, axis=0).A1

# Sort by frequency
lemma_sorted_indices = lemma_doc_frequencies.argsort()

print("\n--- Lemmatization-based Analysis ---")
print(f"Total number of documents: {X_lemmatized.shape[0]}")

print("\nWords appearing in most documents (Lemmatization):")
for i in lemma_sorted_indices[::-1][:10]: # Top 10 most frequent by document
    print(f"'{lemma_vocab[i]}': appears in {lemma_doc_frequencies[i]} documents")

print("\nWords appearing in very few documents (Lemmatization):")
for i in lemma_sorted_indices[:10]: # Top 10 least frequent by document
    print(f"'{lemma_vocab[i]}': appears in {lemma_doc_frequencies[i]} documents")

--- Stemming-based Analysis ---
Total number of documents: 100

Words appearing in most documents (Stemming):
'the': appears in 51 documents
'and': appears in 28 documents
'is': appears in 19 documents
'product': appears in 15 documents
'not': appears in 13 documents
'but': appears in 13 documents
'wa': appears in 13 documents
'it': appears in 12 documents
'thi': appears in 9 documents
'to': appears in 8 documents

Words appearing in very few documents (Stemming):
'about': appears in 1 documents
'you': appears in 1 documents
'actign': appears in 1 documents
'advertis': appears in 1 documents
'attent': appears in 1 documents
'averag': appears in 1 documents
'bad': appears in 1 documents
'basic': appears in 1 documents
'beginn': appears in 1 documents
'best': appears in 1 documents

--- Lemmatization-based Analysis ---
Total number of documents: 100

Words appearing in most documents (Lemmatization):
'product': appears in 15 documents
'good': appears in 8 documents
'nan': appears in 7 documents
'quality': appears in 7 documents
'experience': appears in 7 documents
'nice': appears in 6 documents
'work': appears in 5 documents
'performance': appears in 5 documents
'service': appears in 4 documents
'worth': appears in 4 documents

Words appearing in very few documents (Lemmatization):
'actign': appears in 1 documents
'advertised': appears in 1 documents
'amazing': appears in 1 documents
'annoying': appears in 1 documents
'anything': appears in 1 documents
'anyone': appears in 1 documents
'apart': appears in 1 documents
'attention': appears in 1 documents
'beginner': appears in 1 documents
'basic': appears in 1 documents

# Discussion of significance in text classification:
Words appearing in most documents (high document frequency) are often common words (even after stop-word removal, some general words might remain) or domain-specific terms that are present across nearly all texts. While they might be useful for understanding the general topic of a corpus, they often have low understanding for differentiating between different classes (e.g., positive vs. negative sentiment) because they don't strongly associate with any particular class.

Words appearing in very few documents (low document frequency) are rare terms. They can be highly discriminative if they strongly indicate a specific class. If a word only appears once or twice, its presence might be coincidental, or it might be a misspelling. In many text classification tasks, very rare words are often removed (e.g., by setting a minimum document frequency threshold in CountVectorizer) to reduce the dimensionality of the feature space and improve model robustness, as they can lead to overfitting or computational inefficiency.